---
global:
  repoURL: test
  targetRevision: main

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

aapManifest:
  key: secret/data/hub/aap-manifest

aap:
  eda_disabled: false
  hub_disabled: true
  lightspeed_disabled: true

configJob:
  image: quay.io/rhn_support_mbaldess/ansible-aap-config-container:latest
  schedule: "10 */2 * * *"
  activeDeadlineSeconds: 3600
  imagePullPolicy: Always
  configTimeout: 1800

serviceAccountName: aap-config-sa
serviceAccountNamespace: ansible-automation-platform

# Validation job configuration
validationJob:
  disabled: false
  activeDeadlineSeconds: 600

# RBAC configuration using vp-rbac subchart
vp-rbac:
  serviceAccounts:
    aap-config-sa:
      namespace: ansible-automation-platform
      roleBindings:
        roles:
          - view-all
          - external-secrets-validator
          - create-secrets
        clusterRoles:
          - view-routes

  clusterRoles:
    view-routes:
      rules:
      - apiGroups: ["route.openshift.io"]
        resources: ["routes"]
        verbs: ["get", "list", "watch"]
    
  roles:
    create-secrets:
      rules:
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["create"]
     
    view-all:
      rules:
      - apiGroups: ["*"]
        resources: ["*"]
        verbs: ["get", "list", "watch"]
    
    # RBAC for external secrets validation (namespace-scoped)
    external-secrets-validator:
      rules:
      - apiGroups: ["external-secrets.io"]
        resources: ["externalsecrets"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["authorization.k8s.io"]
        resources: ["selfsubjectrulesreviews"]
        verbs: ["create"]
