---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome-deployment
  labels:
    app: selenium-node-chrome
    name: selenium-node-chrome
spec:
  replicas: 2
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      containers:
        - name: selenium-node-chrome
          image: quay.io/validatedpatterns/selenium-node-chrome:136.0-20250828
          env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: '4442'
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: '4443'
            - name: SE_NODE_GRID_URL
              value: 'selenium-hub:4444'
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: 'true'
          ports:
            - containerPort: 4444
              protocol: TCP
            - containerPort: 5555
              protocol: TCP
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              memory: "1024Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      serviceAccountName: toolstack-sa
      serviceAccount: toolstack-sa
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-node-chrome
  labels:
    name: selenium-node-chrome
spec:
  type: ClusterIP
  selector:
    app: selenium-node-chrome
    browser: chrome
  ports:
    - name: nodeport
      protocol: TCP
      port: 5555
      targetPort: 5555
    - name: node-port-grid
      protocol: TCP
      port: 4444
      targetPort: 4444
---

