---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aap-entitlement-playbook-cm
data:
  entitle.yml: |
{{ .Files.Get "ansible-entitlement-playbook.yaml" | indent 4 }}  
---
apiVersion: batch/v1
kind: Job
metadata:
  name: aap-config-bootstrap-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 99
  template:
    spec:
      activeDeadlineSeconds: 600
      restartPolicy: Never
      serviceAccountName: {{ $.Values.serviceAccountName }}
      volumes:
        - name: scratch-space
          emptyDir:
            sizeLimit: 1Gi
        - name: aap-manifest
          secret:
            secretName: aap-manifest
        - name: aap-admin-password
          secret:
            secretName: aap-admin-password
        - name: aap-entitlement-playbook
          configMap:
            name: aap-entitlement-playbook-cm
        - name: helm-values
          configMap:
            name: helm-values
      initContainers:
        - name: init
          image: {{ .Values.configJob.image }}
          imagePullPolicy: {{ $.Values.configJob.imagePullPolicy }}
          env:
            - name: HOME
              value: /pattern-home
          workingDir: /pattern-home
          command:
            - /bin/bash
            - -c
            - >
              base64 -d /pattern-home/aap-manifest/b64content > /pattern-home/aap_manifest.zip &&
              git clone --recurse-submodules --single-branch --branch "{{ .Values.global.targetRevision }}"
              -- "{{ .Values.global.repoURL }}" /pattern-home/git
          volumeMounts:
            - name: scratch-space
              mountPath: /pattern-home
            - name: aap-manifest
              mountPath: /pattern-home/aap-manifest
              readOnly: true
      containers:
        - name: config
          image: {{ .Values.configJob.image }}
          imagePullPolicy: {{ $.Values.configJob.imagePullPolicy }}
          env:
            - name: HOME
              value: /pattern-home
          workingDir: /pattern-home/agof_repo
          command:
            - /bin/bash
            - -c
            - > 
              ansible-playbook -vvv /pattern-home/git/ansible/aap-playbooks/entitle-manifest.yml
          volumeMounts:
            - name: scratch-space
              mountPath: /pattern-home
            - name: aap-admin-password
              mountPath: /pattern-home/aap-admin-password
              readOnly: true
            - name: aap-entitlement-playbook
              mountPath: /opt/ansible/playbooks
              readOnly: true
            - name: helm-values
              mountPath: /pattern-home/helm-values
              readOnly: true