apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: ansible-automation-platform
spec:
  api:
    log_level: INFO
    replicas: 1
  database:
    idle_disabled: false
    postgres_data_volume_init: true
  no_log: false
  redis_mode: standalone
  route_tls_termination_mechanism: Edge
