{{- if not $.Values.configJob.disabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: agof-config-cronjob
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  schedule: {{ $.Values.configJob.schedule | quote }}
  # if previous Job is still running, skip execution of a new Job
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          activeDeadlineSeconds: {{ $.Values.configJob.activeDeadlineSeconds }}
          {{- include "aap-config.app.configjobspec" $ | nindent 10 }}
{{- end }}{{/* if not $.Values.configJob.disabled */}}
