apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  volumes:
  serviceAccountName: aap-controller
  initContainers:
    - name: init
      image: quay.io/rhn_support_mbaldess/ansible-aap-config-container:latest
      workingDir: /var/aap-git
      command:
        - /bin/bash
        - -c
        - >
          git clone --recurse-submodules --single-branch --branch "bandini-aap-test"
          -- "https://github.com/validatedpatterns-sandbox/vp-frankfurt" /var/aap-git/repo
      volumeMounts:
        - name: scratch-space
          mountPath: /var/aap-git
  containers:
    - name: debug
      image: quay.io/rhn_support_mbaldess/ansible-aap-config-container:latest
      command: ["/usr/bin/sleep", "infinity"]
      volumeMounts:
        - name: helm-values
          mountPath: "/var/helm-values/"
          readOnly: true
        - name: aap-manifest-volume
          mountPath: "/var/aap-manifest/"
          readOnly: true
        - name: aap-admin-password
          mountPath: "/var/aap-admin-password/"
          readOnly: true
        - name: scratch-space
          mountPath: "/var/aap-git/"
  volumes:
    - name: helm-values
      configMap:
        name: helm-values
    - name: aap-admin-password
      secret:
        secretName: aap-admin-password
    - name: aap-manifest-volume
      secret:
        secretName: aap-manifest
    - name: scratch-space
      emptyDir:
        sizeLimit: 5Gi
