apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  serviceAccountName: aap-controller
  containers:
    - name: debug
      image: quay.io/rhn_support_mbaldess/ansible-aap-config-container:latest
      command: ["/usr/bin/sleep", "infinity"]
      volumeMounts:
        - name: aap-manifest-volume
          mountPath: "/var/aap-manifest/"
          readOnly: true
        - name: aap-admin-password
          mountPath: "/var/aap-admin-password/"
          readOnly: true
  volumes:
    - name: aap-admin-password
      secret:
        secretName: aap-admin-password
    - name: aap-manifest-volume
      secret:
        secretName: aap-manifest
