---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: aap-manifest
  annotations:
      argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: aap-manifest
  dataFrom:
  - extract:
      key: {{ .Values.aapManifest.key }}
