apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  #storageClassName: "${STORAGE_CLASS_NAME}"
---
