apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels: 
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Values.name }}     
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.env.security_admin_pass }}
          ports:
            - containerPort: {{ .Values.container_port}}
          resources:
            requests:
              cpu:  {{ .Values.resources.cpu_request }}
              memory: {{ .Values.resources.memory_request }}
            limits:
              cpu: {{ .Values.resources.cpu_limit }}
              memory: {{ .Values.resources.memory_limit }}
          args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--web.console.libraries=/usr/share/prometheus/console_libraries"
          - "--web.console.templates=/usr/share/prometheus/consoles"    
          volumeMounts:
            - name: {{ .Values.volumeMount.name }}
              mountPath: {{ .Values.volumeMount.path }}  
            - name: {{ .Values.volumeMount.name2 }}
              mountPath: {{ .Values.volumeMount.path2 }}
              subPath: {{ .Values.volumeMount.subpath }}
      serviceAccount: {{ .Values.serviceAccount.name }}
      volumes:
        - name: {{ .Values.volumes.name }}
          persistentVolumeClaim: 
            claimName: {{ .Values.name }}-pvc
        - name: {{ .Values.volumes.name2 }}
          configMap:
            name: {{ .Values.configmap.name }}
      
