apiVersion: v1
kind: Service
metadata:
  name: {{ include "selenium-node-chrome.name" . }}
  labels:
    {{- include "selenium-node-chrome.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
  {{- end }} 
  selector:
    {{- include "selenium-node-chrome.selectorLabels" . | nindent 4 }}
