---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged'
  namespace: devops
  rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - pods
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:anyuid'
  namespace: devops
  rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - pods
---
