apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  ports:
    - name: sonarqube
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: sonarqube
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: Route for SonarQube's HTTP service.
  name: sonarqube
  labels:
    app: sonarqube
spec:
  to:
    kind: Service
    name: sonarqube
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      securityContext:
        fsGroup: 999  # Ensures Elasticsearch can write logs
      containers:
        - name: sonarqube
          image: quay.io/validatedpatterns/sonarqube:lts-community
          imagePullPolicy: IfNotPresent        
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
              value: "true"  # Disable strict bootstrap checks
          securityContext:
            runAsUser: 1000  # Ensure SonarQube does NOT run as root
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /api/system/status
              port: 9000
            initialDelaySeconds: 80
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/system/status
              port: 9000
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              cpu: "1"
              memory: "3Gi"  # Increased to prevent OOM
            limits:
              cpu: "2"
              memory: "4Gi"
          volumeMounts:
            - mountPath: /opt/sonarqube/data
              name: sonarqube-data
      serviceAccount: toolstack-sa
      volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

