---
# defaults file for clusterdeploy
create: false
destroy: false

user_provided_credentials: false

cluster:
  namespace: hive
  clusterset: default

cloudConfig:
  azure:
    cloudName: AzurePublicCloud


