---
# defaults file for clusterdeploy
create: "{{ create_or_destroy_input | default('false') }}"
destroy: "{{ create_or_destroy_input | default('false')}}"
# Render templates for debugging
debug_task: false

user_provided_credentials: false

cluster:
  namespace: hive
  clusterset: default

cloudConfig:
  azure:
    cloudName: AzurePublicCloud
