---
# defaults file for clusterdeploy
create: "{{ create_cluster_input | default('false') }}"
destroy: "{{ destroy_cluster_input | default('false') }}"
# Render templates for debugging
debug_task: false

user_provided_credentials: false

cluster:
  namespace: hive
  clusterset: default

cloudConfig:
  azure:
    cloudName: AzurePublicCloud
