{{- if .Values.k10VolumeSnapshotClasses.annotate }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kasten-io.fullname" . }}-vsc-annotator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "kasten-io.labels" . | nindent 4 }}
    app.kubernetes.io/component: vsc-annotator
rules:
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotclasses"]
  verbs: ["get", "list", "patch", "update"]
{{- end }}