---
- name: "Destroy {{ cluster.name }}"
  kubernetes.core.k8s:
    state: absent
    api_version: hive.openshift.io/v1
    kind: ClusterDeployment
    name: "{{ cluster.name }}"
    namespace: "{{ cluster.namespace }}"
    wait: false
  register: destroy_cluster
  when: destroy

- name: "Wait forClusterDeployment to be fully deleted: {{ cluster.name }}"
  kubernetes.core.k8s_info:
    api_version: hive.openshift.io/v1
    kind: ClusterDeployment
    name: "{{ cluster.name }}"
    namespace: "{{ cluster.namespace }}"
  register: deletion_status
  until:
    - deletion_status.resources is not defined or deletion_status.resources | length == 0
  retries: 120
  delay: 10
  when: destroy

- name: "remove {{ cluster.name }} managedCluser resource"
  kubernetes.core.k8s:
    state: absent
    api_version: cluster.open-cluster-management.io/v1
    kind: ManagedCluster
  when: destroy

- name: "Remove namespace {{ cluster.namespace }}"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ cluster.namespace }}"
    state: absent
  when:
    - destroy
    - deletion_status is succeeded

- name: "Remove {{ deployment_config_dir }}"
  ansible.builtin.file:
    state: absent
    path: "{{ deployment_config_dir }}"
  when:
    - destroy
    - deletion_status is succeeded
