---
- name: "Destroy {{ cluster.name }}"
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', clusterDeployment.yaml.j2') | from_yaml }}"
    wait: false
  register: clusterdeployment
  when: destroy

- name: Wait for cluster deployment {{ cluster.name }} to be fully deleted
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ClusterDeployment
    name: "{{ cluster.name }}"
    namespace: "{{ cluster.namespace }}"
  register: deployment_status
  until: deployment_status.resources | length == 0
  retries: 60
  delay: 5


#- name: "Remove {{ cluster.namespace }} when {{ cluster.name }} has been destroyed"
#  kubernetes.core.k8s:
#    name: {{ cluster.namespace }}
#    api_version: v1
#    kind: Namespace
#    state: absent
#  when: 
