---
# tasks file for clusterdeploy
- name: "Create directory {{ cluster.name }}"
  ansible.builtin.file:
    name: "{{ cluster.name }}"
    state: directory
    mode: "0755"
  when: create or debug_task

- name: "Set deployment_config_dir fact"
  ansible.builtin.set_fact:
    deployment_config_dir: "{{ cluster.name }}"

- name: "Create cluster secrets - if using user_provided_credentials"
  ansible.builtin.include_tasks: clusterSecrets.yml
  when: user_provided_credentials

- name: "Generate install-config for the clusterdeployment"
  ansible.builtin.include_tasks: create-install-config.yml
  when: create or debug_task

- name: "Create cluster tasks"
  ansible.builtin.include_tasks: createCluster.yml
  when: create

# - name: "Destroy cluster tasks"
#  ansible.builtin.include_tasks: destroyCluster.yml
#  when: destroy
#
# - name: "Run debug play"
#  ansible.builtin.include_tasks: debug_task.yml
#  when: debug_task
