---
# tasks file for clusterdeploy
- name: "Create {{ cluster.name }} directory"
  ansible.builtin.file:
    name: "{{ cluster.name }}"
    state: directory
    mode: 0755
  when: create

- name: "Set deployment_config_dir fact"
  ansible.builtin.set_fact:
    deployment_config_dir: "{{ cluster.name }}"

#- name: "Create install-config template"
#  ansible.builtin.template:
#    src: install-config.yaml.j2
#    dest: "{{ deployment_config_dir }}/{{ cluster.cloud.provider }}-install-config.yaml"

- ansible.builtin.include_tasks: createCluster.yml
  when: create

- ansible.builtin.include_tasks: destroyCluster.yml
  when: destroy
