{{- if .Values.ldap.groupsync.enabled }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: ldap-groupsync
  namespace: group-sync-operator
spec:
  providers:
  - ldap:
      credentialsSecret:
        name: ldap-group-sync
        namespace: group-sync-operator
      {{- with .Values.ldap }}
      whitelist:
      - {{ .whitelistDN }},{{ .groupsDN }},{{ .baseDN }}
      insecure: {{ .insecure }}
      rfc2307:
        groupMembershipAttributes:
        - member
        groupNameAttributes:
        - cn
        groupUIDAttribute: dn
        groupsQuery:
          baseDN: "{{ .groupsDN }},{{ .baseDN }}"
          derefAliases: never
          filter: (objectClass=groupofnames)
          scope: sub
        tolerateMemberNotFoundErrors: true
        tolerateMemberOutOfScopeErrors: true
        userNameAttributes:
        - cn
        userUIDAttribute: dn
        usersQuery:
          baseDN: "{{ .usersDN }},{{ .baseDN }}"
          derefAliases: never
          scope: sub
      url: {{ .url }}
      {{- end }}
    name: ldap
{{- end }}
