---
- name: Create Route53 DNS record for the instance
  hosts: localhost
  gather_facts: false
  collections:
  - amazon.aws
  tasks:
  - name: Create/Update A record
    amazon.aws.route53:
      zone: "{{ hosted_zone }}"
      record: "{{ fqdn }}"
      type: A
      ttl: 60
      value: "{{ hostvars['localhost']['idm_public_ip'] | default(idm_public_ip, true) }}"
      overwrite: true
      state: present
    register: r53

  - name: Show DNS
    ansible.builtin.debug:
      var: r53
