apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.name" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.port }}-{{ .Values.service.protocol | lower}}
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
