{{- if .Values.ldap.oauth.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-secret
  namespace: openshift-config
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ldap-secret
    creationPolicy: Owner
  data:
    - secretKey: bindPassword
      remoteRef:
        key: secret/data/hub/ldap
        property: password
{{- end }}
