kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  {{ .Values.Role.privileged_name }}
  namespace: {{ .Values.Role.namespace }}
  rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - pods
