---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: eso-pullsecret
  namespace: hive
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: global-pullsecret
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
    data:
      .dockerconfigjson: '{{ `{{ ".dockerconfigjson" | toString }}` }}'
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: "pushsecrets/global-pull-secret"
