---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: global-pullsecret
  namespace: hive
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: global-pullsecret
    creationPolicy: Owner
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: "pushsecrets/global-pull-secret"
      property: docker
