apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: eso-aws-creds
  namespace: hive
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: aws-creds
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.awsCreds.key }}
