# Default values for oauth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ldap:
  url: "ldap://ldap-server.example.com:389"
  insecure: true
  baseDN: "cn=accounts,dc=example,dc=com"
  bindDN: "uid=reader"
  usersDN: "cn=users"
  groupsDN: "cn=groups"
  oauth:
    enabled: true
