apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels: 
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Values.name }}
          securityContext:
            runAsUser: {{ .Values.securityContext.value }}        
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: {{ .Values.env.nexus_serch_index }}
            - name: TZ
              value: {{ .Values.env.vm_params }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port1 }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.port2 }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.port3 }}
              protocol: TCP
          resources:
            requests:
              cpu:  {{ .Values.resources.cpu_request }}
              memory: {{ .Values.resources.memory_request }}
            limits:
              cpu: {{ .Values.resources.cpu_limit }}
              memory: {{ .Values.resources.memory_limit }}
      serviceAccount: {{ .Values.serviceAccount.name }}
