apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels: 
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Values.name }}  
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SE_EVENT_BUS_HOST
              value: {{ .Values.env.event_bus_host }}
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: {{ .Values.env.event_bus_publish_port }}
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: {{ .Values.env.event_bus_subscribe_port }}
            - name: SE_NODE_GRID_URL
              value: {{ .Values.env.node_grid_url }}
            - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
              value: {{ .Values.env.log4j_lookup }}
          ports:
            - containerPort: {{ .Values.container.port1 }}
              protocol: {{ .Values.container.protocol }}
            - containerPort: {{ .Values.container.port2 }}
              protocol: {{ .Values.container.protocol }}
          resources:
            requests:
              cpu:  {{ .Values.resources.cpu_request }}
              memory: {{ .Values.resources.memory_request }}
            limits:
              cpu: {{ .Values.resources.cpu_limit }}
              memory: {{ .Values.resources.memory_limit }}
          volumeMounts:
            - name: {{ .Values.volumeMount.name }}
              mountPath: {{ .Values.volumeMount.path }}
      serviceAccount: {{ .Values.serviceAccount.name }}
      volumes:
        - name: {{ .Values.volume.name }}
          emptyDir: { "medium": "Memory" }
