---
# Helper tasks to retrieve AAP admin token from OpenShift secret
# Include this file in other playbooks that need to use the AAP token

- name: Get AAP config access secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: aap-config-access
    namespace: "{{ aap_namespace }}"
  register: aap_token_secret

- name: Fail if AAP token secret not found
  ansible.builtin.fail:
    msg: "AAP config access secret not found. Run aap_postinstall_create_admin_token.yml first."
  when: aap_token_secret.resources | length == 0

- name: Extract AAP connection details from secret
  ansible.builtin.set_fact:
    aap_admin_token: "{{ aap_token_secret.resources[0].data.token | b64decode }}"
    aap_hostname: "{{ aap_token_secret.resources[0].data.hostname | b64decode }}"
    aap_username: "{{ aap_token_secret.resources[0].data.username | b64decode }}"
    aap_validate_certs: "{{ aap_token_secret.resources[0].data.validate_certs | b64decode | bool }}"
  when: aap_token_secret.resources | length > 0

- name: Debug AAP connection details
  ansible.builtin.debug:
    msg:
      - "AAP URL: https://{{ aap_hostname }}"
      - "AAP Username: {{ aap_username }}"
      - "Token available: {{ 'Yes' if aap_admin_token is defined else 'No' }}"
      - "Validate certs: {{ aap_validate_certs }}"
    verbosity: 1
