apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels: 
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      initContainers:
        - name: {{ .Values.initContainer.name }}
          image: {{ .Values.initContainer.image }}
          command: [ "/bin/sh","-c" ]
          resources:
            requests:
              cpu: {{ .Values.initContainer.resources.cpu_request }}
              memory: {{ .Values.initContainer.resources.memory_request }}
            limits:
              cpu: {{ .Values.initContainer.resources.cpu_limit }}
              memory: {{ .Values.initContainer.resources.memory_limit }}
          args: [ "chown -R 200:200 /nexus-data" ]
          volumeMounts:
            - name: {{ .Values.volumeMount.name }}
              mountPath: {{ .Values.volumeMount.path }}
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Values.name }}
          securityContext:
            runAsUser: {{ .Values.securityContext.value }}        
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NEXUS_SEARCH_INDEX_REBUILD_ON_STARTUP
              value: {{ .Values.env.nexus_serch_index }}
            - name: INSTALL4J_ADD_VM_PARAMS
              value: {{ .Values.env.vm_params }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            requests:
              cpu:  {{ .Values.resources.cpu_request }}
              memory: {{ .Values.resources.memory_request }}
            limits:
              cpu: {{ .Values.resources.cpu_limit }}
              memory: {{ .Values.resources.memory_limit }}
          volumeMounts:
            - name: {{ .Values.volumeMount.name }}
              mountPath: {{ .Values.volumeMount.path }}
      serviceAccount: {{ .Values.serviceAccount.name }}
      volumes:
        - name: {{ .Values.volumeMount.name }}
          persistentVolumeClaim: 
            claimName: {{ .Values.name }}-pv
